global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'go_exporter'
    static_configs:
      - targets: [ 'go-supply-chain-track:3000' ]

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090