basePath: /api/v1
definitions:
  dto.HealthResponse:
    properties:
      status:
        type: string
      success:
        type: boolean
      timestamp:
        type: integer
      version:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API supply chain tracking system
  title: Supply Chain API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns service health status and version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthResponse'
      summary: Show the health status of the service
      tags:
      - Health
swagger: "2.0"
